### ISSUE TITLE
idの指定は一意にしたい

### ISSUE THREAD

**Issue by shoya123** [conpota03/Scenario-Spotlight#1]
`id`の指定はユニーク（一意）にしたい。

`id="sbox2"`は一つだけにする。
`name`も別の名前をつける。

https://github.com/conpota03/scenario-review/blob/30ee459fc695806486af339875c3370a7bd7b34a/index.html#L31-L34

**Comment by conpota03** [comment]
<input class="sbox1" name="s1" type="text" placeholder="キーワード・タグ" />
                <input class="sbox1" name="s2" type="text" placeholder="システム" />
                <input class="sbox1" name="s3" type="text" placeholder="PL人数" />
                <input class="sbox1" name="s4" type="text" placeholder="プレイ時間" />
に変更
